### ISSUE TITLE
[Chrome] Not working if refreshing after opening devtools

### ISSUE THREAD

**Issue by Akshay-akkay** [david-fong/detect-devtools-via-debugger-heartstop#2]

**Comment by david-fong** [comment]
I can't reproduce this issue. Please give exact details about what browser you are using. check the `about:version` page of your browser.

**Comment by Akshay-akkay** [comment]
Oh! I'm really sorry, actually, it was an issue in my code and not the library. 
Still, thanks for the fast reply.
We can close this issue.
